Deployment:
  scenario: small_string
  confluence: memo
  id: small_string*
  owner_id: small_string
  org_ids: small_string
  site_id: small_string
  device_id: small_string
  activate: boolean
  name: small_string
  description: memo
  constraint_ids: string
  coordinate_system: string
  context_type: string

